services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzTFABundle\Controller\TFAController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $providersConfig: $providers;edgar_ez_tfa$
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    Edgar\EzTFABundle\Controller\EmailAuthController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $providers: $providers;edgar_ez_tfa$
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    Edgar\EzTFABundle\Controller\SMSAuthController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $providers: $providers;edgar_ez_tfa$
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    Edgar\EzTFABundle\Controller\SMSRegisterController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $provider: "Edgar\\EzTFABundle\\Provider\\SMS\\SMSProvider"
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    Edgar\EzTFABundle\Controller\U2FAuthController:
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    Edgar\EzTFABundle\Controller\U2FRegisterController:
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]
