edgar.eztfa.menu:
    path: /user/profile/tfa
    defaults:
        _controller: 'EdgarEzTFABundle:TFA:menu'

tfa_list:
    path: /list
    methods: [GET]
    defaults: { _controller: 'EdgarEzTFABundle:TFA:list' }

tfa_click:
    path: /click/{provider}
    methods: [GET]
    defaults: { _controller: 'EdgarEzTFABundle:TFA:click' }
    requirements:
        provider: "[a-z0-9]+"

tfa_registered:
    path: /registered/{provider}
    methods: [GET]
    defaults: { _controller: 'EdgarEzTFABundle:TFA:degistered' }
    requirements:
        provider: "[a-z0-9]+"

tfa_reinitialize:
    path: /reinitialize/{provider}
    methods: [GET]
    defaults: { _controller: 'EdgarEzTFABundle:TFA:reinitialize' }
    requirements:
        provider: "[a-z0-9]+"

tfa_cancel:
    path: /cancel/{provider}
    methods: [GET]
    defaults: { _controller: 'EdgarEzTFABundle:TFA:cancel' }
    requirements:
        provider: "[a-z0-9]+"

tfa_provider_email:
    resource: "@EdgarEzTFABundle/Resources/config/routing_email.yml"
    prefix: /email

tfa_provider_sms:
    resource: "@EdgarEzTFABundle/Resources/config/routing_sms.yml"
    prefix: /sms

tfa_provider_u2f:
    resource: "@EdgarEzTFABundle/Resources/config/routing_u2f.yml"
    prefix: /u2f


