imports:
    - { resource: controllers.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzTFABundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: edgar_ezuiprofile.menu_configure.profile_sidebar_left, method: onMenuConfigure }

    Edgar\EzTFABundle\EventListener\TFAListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onRequest }

    Edgar\EzTFA\Handler\AuthHandler:
        public: true
        arguments:
            $providersConfig: $providers;edgar_ez_tfa$

    Edgar\EzTFABundle\Provider\U2F\Event\RegistrationListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: edgarez_tfa_u2f.register, method: onRegister }

    Edgar\EzTFABundle\Provider\Email\EmailProvider:
        public: true
        tags:
          - { name: edgar.tfa.provider, alias: email }

    Edgar\EzTFABundle\Provider\SMS\SMSProvider:
        public: true
        tags:
          - { name: edgar.tfa.provider, alias: sms }

    Edgar\EzTFABundle\Provider\U2F\U2FProvider:
        public: true
        tags:
          - { name: edgar.tfa.provider, alias: u2f }

    Edgar\EzTFABundle\Provider\U2F\Form\Constraints\AuthCodeValidator: ~

    Edgar\EzTFABundle\Provider\Email\Form\Constraints\AuthCodeValidator:
        arguments:
            - "@session"
        tags:
            - { name: validator.constraint_validator, alias: edgareztfa.email.auth.contraint }

    Edgar\EzTFABundle\Provider\SMS\Form\Constraints\AuthCodeValidator:
        arguments:
            - "@session"
        tags:
            - { name: validator.constraint_validator, alias: edgareztfa.sms.auth.contraint }
